
---
- name: create a single vm from template 
  hosts: localhost
  become: false
  gather_facts: false
  
  vars_files:
    - multiplevmvars.yml
    - password.yml
  
  tasks:
  - name:  Clone a virtual machine from Linux template and customize
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter: "{{ datacenter }}"
      state: poweredon
      folder: "{{ folder }}"
      template: "{{ template }}"
      name: "{{ item.vm_name }}"
      cluster: "{{ cluster }}"
      datastore: "{{ datastore }}"
      disk:
        - size_gb: "{{ item.data_disk_size }}"
          type: thin
          datastore: "{{ datastore }}"
      hardware:
        memory_mb: "{{ item.memory }}"
        num_cpus: "{{ item.cpu_cores }}"
        num_cpu_cores_per_socket: "{{ cpu_cores }}"
        scsi: paravirtual
        hotadd_cpu: true
        hotremove_cpu: true
        hotadd_memory: false
        version: 12 # Hardware version of virtual machine            
      networks:
        - name: "{{ item.network }}"
          ip: "{{ item.ip_address }}"
          netmask: "{{ netmask }}"
          gateway: "{{ gateway }}"
      wait_for_ip_address: true
      customization:
        domain: "{{ item.guest_domain }}"
        dns_servers:
          - "{{ dns_server1 }}"
        dns_suffix:
          - "{{ dns_suffix }}"
        script_text: |
          #!/bin/bash
          touch /tmp/touch-from-playbook
    with_items: "{{ vms }}" 
    # delegate_to: localhost